blog/urls.py
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 13 17:12:18 2017

@author: crist
"""

from django.conf.urls import url


from . import views

app_name = 'blog'

urlpatterns = [
        url(r'^index/$', views.index, name='index'),
        url(r'^search/$', views.search, name='search'),
        url(r'^(?P<post_id>[0-9]+)/$', views.detail, name='detail'),    
        url(r'^topic/(?P<topic>[\w\-]+)/$', views.topic, name='topic'),
        url(r'^tag/(?P<tag>[\w\-]+)/$', views.tags, name='tags'),
        ]

hindsight1/urls.py
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 13 17:12:18 2017

@author: crist
"""

from django.conf.urls import url

from . import views

#this tells django these urls belong to the 'hindsight1' app, when referencing
#from a template with the {%url%} tag. 
app_name = 'hindsight1'

urlpatterns = [url(r'^game/$', views.ranking, name='ranking'),
              url(r'^result/$', views.result, name='result'),
              url(r'^play/$', views.play, name='play'),
              url(r'^ranking/$', views.ranking, name='ranking'),
              url(r'^dashboard/$', views.perf_dashboard, name='dashboard'),
              
              
              
              ]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from .sitemaps import MainSitemap
from blog.sitemaps import BlogSitemap


urlpatterns = [
    url(r'^game/', include('hindsight1.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.about, name='home'),
    url(r'^myhome/(?P<username>[\w\-]+)/', views.myhome, name='myhome'),        
    url(r'^about/$', views.about, name='about'), 
]


#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),

]

#Add sitemapts

sitemaps = {
        'blog': BlogSitemap(),
        'main': MainSitemap(),
        }

urlpatterns += [
        url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

#Add Markdown
urlpatterns += [
    url(r'^markdownx/', include('markdownx.urls')),
]

#Add media path
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hindsight1/models.py
import datetime
from pandas.tseries.offsets import BDay
from random import randint

from django.db import models

from django.contrib.postgres.fields import ArrayField
from django_pandas.io import read_frame
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django import forms
from django.utils import timezone

from postgres_copy import CopyManager


class Sp100QuerySet(models.QuerySet):
    
    def random_company(self):
        count = self.all().count()
        random_index = randint(0, count - 1)
        return self.all()[random_index]

    def get_tickers(self, number):
        tickers=[]
        for index in range(number):
            t = self.random_company().ticker
            tickers.append(t)
        return tickers  
    
    def get_sector(self, t):
        sector = self.get(ticker=t).sector
        return sector

    def get_industry(self, t):
        industry = self.get(ticker=t).industry
        return industry
   
class Sp100(models.Model):
    ticker = models.CharField(max_length=100, primary_key=True)
    security = models.CharField(max_length=100)
    sector = models.CharField(max_length=100)
    industry = models.CharField(max_length=100)
    isin = models.CharField(max_length=100)
    objects = CopyManager()
    playcompanies = Sp100QuerySet.as_manager()
    
    def __str__(self):
        return self.security
 

class PricesQuerySet(models.QuerySet):

    def min_date(self):
        min_date = self.earliest('date').date
        return min_date
    
    def max_date(self):
        max_date = self.latest('date').date
        return max_date
        
    def date_pool(self):
        dates = self.order_by('date').distinct()
        return dates
    
    #start date of play
    def rand_date(self):
        min_date = self.min_date()
        max_date = self.max_date()
        checks = True
        while checks:
            count = self.all().count()
            random_index = randint(0, count - 1)
            rand_date = self.all()[random_index].date
            # Check date has 6M of forward and backwards history
            ret_start = Prices.start_date(rand_date)
            ret_end = Prices.end_date(rand_date)
            if ret_start >= min_date and ret_end <= max_date:
                checks = False
        return rand_date

    def random_company(self, date):
        count = self.filter(date=date).count()
        random_index = randint(0, count - 1)
        return self.filter(date=date)[random_index]

    def get_tickers(self, number, date):
        tickers=[]
        for index in range(number):
            t = self.random_company(date).ticker
            tickers.append(t)
        return tickers  
        
    def start_play(self, number=5):
        checks = 0
        while checks < number:
            date = self.rand_date()
            #get tickers, and check tey are 5 distinct
            while True:
                tickers = self.get_tickers(number=number, date=date)
                if len(set(tickers)) == number:
                    break
            #check if all 5 tickers have 6M forward and trailing data
            start = Prices.start_date(date)
            end = Prices.end_date(date)
            for ticker in tickers:
                try:
                    self.ticker_ror(ticker, start=start, end=date)
                    trailing = True
                except:
                    pass
                    trailing = False
                try:    
                    self.ticker_ror(ticker, start=date, end=end)
                    forward = True
                except:
                    pass
                    forward = False
                if trailing and forward:
                    checks+=1
        return date, tickers
                
                

    def price_ts(self, t, start, end):
        """
        get price TS for a single ticker, from start date to end date
        """
        prices=self.filter(ticker=t).order_by('date')
        df_p=read_frame(prices, fieldnames=['date', 'ticker', 'price'])
        df_p.set_index('date', inplace=True)
        prices_ts=df_p.loc[start:end]
        prices_ts.columns=['ticker', t]
        prices_ts.drop(['ticker'], axis=1, inplace=True)
        return prices_ts
 
    def ticker_ror(self, t, start, end):
        """
        get price datapoint at start and end date, calculate return
        """
        price_t1 = self.get(ticker=t, date=end).price
        price_t0 = self.get(ticker=t, date=start).price
        ror=price_t1/price_t0-1
        return ror


class Prices(models.Model):
    date = models.DateField(null=True)
    ticker = models.CharField(max_length=10)
    price = models.FloatField(default=1.0)
    objects = CopyManager()
    playprices = PricesQuerySet.as_manager()

    def __str__(self):
        return '{} {}'.format(self.ticker, self.date.strftime('%m/%d/%Y'))
    
    #6 month prior date
    def start_date(rand_date):
        ret_start=(rand_date-BDay(130)).date()
        return ret_start
        
    #6 month forward date
    def end_date(rand_date):
        ret_start=(rand_date+BDay(130)).date()
        return ret_start


class PlayRecordQuerySet(models.QuerySet):
    def strategy_ror(self, weights, tickers=None, date=None, play_id=None):
        if play_id != None:
            tickers = self.get(pk=play_id).companies
            date = self.get(pk=play_id).play_rand_date
        rors=[]
        start = date
        end = Prices.end_date(date)
        for ticker in tickers:
            ror = Prices.playprices.ticker_ror(ticker, start, end)
            rors.append(ror)
        strategy_ror = sum([a*b for a,b in zip(weights, rors)])
        return strategy_ror    
    
    def get_past_rors(self, user):
        plays = self.filter(user=user, played=True).order_by('play_time')
        df=read_frame(plays, fieldnames=['strategy_ror', 'play_time'])
        df.set_index('play_time', inplace=True)
        return df

        
    def get_cum_rors(self,user):
        plays = self.filter(user=user, played=True).order_by('play_time')
        df=read_frame(plays, fieldnames=['strategy_ror', 'play_time'])
        df.set_index('play_time', inplace=True)
        df_cum=(1 + df['strategy_ror']).cumprod() - 1
        return df_cum

class PlayRecord(models.Model):
    play_time=models.DateTimeField(default=timezone.now)
    strategy_ror = models.FloatField(default=0.0)
    play_rand_date = models.DateTimeField(default=datetime.datetime.now)
    companies = ArrayField(models.CharField(max_length=10), default=list)
    company_1 = models.FloatField(default=0.0)
    company_2 = models.FloatField(default=0.0)
    company_3 = models.FloatField(default=0.0)
    company_4 = models.FloatField(default=0.0)
    company_5 = models.FloatField(default=0.0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    played = models.BooleanField(default=False)
    objects = PlayRecordQuerySet.as_manager()



class GameInputForm(forms.Form):
    company_1 = forms.IntegerField(widget=forms.NumberInput(attrs={'type':'range', 'min':0, 'max':100, 'step': '5', 'value':0.0}))
    company_2 = forms.IntegerField(widget=forms.NumberInput(attrs={'type':'range', 'min':0, 'max':100, 'step': '5', 'value':0.0}))
    company_3 = forms.IntegerField(widget=forms.NumberInput(attrs={'type':'range', 'min':0, 'max':100, 'step': '5', 'value':0.0}))
    company_4 = forms.IntegerField(widget=forms.NumberInput(attrs={'type':'range', 'min':0, 'max':100, 'step': '5', 'value':0.0}))
    company_5 = forms.IntegerField(widget=forms.NumberInput(attrs={'type':'range', 'min':0, 'max':100, 'step': '5', 'value':0.0}))



#Extend Django User model to include running capital amount
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    capital = models.FloatField(default=1000000)
    
    def __str__(self):
        return self.user


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

hindsight1/views.py
import pandas as pd
import datetime

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

import hindsight1.charts.charts as chart
from .models import GameInputForm, Sp100, Prices, PlayRecord, Profile


def ranking(request):
    rank = Profile.objects.all().order_by('-capital')[:10]
    return render(request, 'hindsight1/ranking.html', context={'rank': rank})


@login_required(login_url='/accounts/login/')
def perf_dashboard(request):
    user = request.user
    capital = user.profile.capital
    # previous plays result
    df_plays = PlayRecord.objects.get_past_rors(user)
    past_chart = chart.chart_bar(df_plays['strategy_ror'], title='Performance History',
                               formatchart='.1%', categories=None, size=(500,500))
    # cumulate returns
    df_cum = PlayRecord.objects.get_cum_rors(user)
    df_capital = (df_cum+1)*1000000
    cum_chart=chart.chart_bar_cum(df_capital, df_cum, title='Cumulate Returns',
                                  categories=False, formatchart='$,.0f', size=(500,500))

    context = {
        'user': user,
        'past_chart': past_chart,
        'cum_chart': cum_chart,
        'capital': capital,
    }
    return render(request, 'hindsight1/performance.html', context)


def result(request):
    weights = request.session['weights'] 
    companies = request.session['companies']
    year = request.session['year']
    month = request.session['month']
    day = request.session['day']
    date = datetime.date(year, month, day)
    user = request.user
    port_ror = PlayRecord.objects.strategy_ror(weights, tickers=companies, date=date)
    if user.is_authenticated:
        play_id = request.session['play_id']
        user.profile.capital = user.profile.capital*(1+port_ror)
        user.save()
        play_object = PlayRecord.objects.get(pk=play_id)
        play_object.strategy_ror = port_ror
        play_object.played = True
        play_object.save()
    end = Prices.end_date(date)
    prices = pd.DataFrame()
    for company in companies:
        prices_t = Prices.playprices.price_ts(company, date, end)
        prices = pd.concat([prices, prices_t], axis=1)
    strat_ts = strategy_ts(prices, weights)
    strat_cum = chart.chart_line(strat_ts, formatchart='.3%', name='Strategy Performance', size=[600,400])
    names=[]
    rors=[]
    for ticker in companies:
        name = Sp100.objects.get(pk=ticker).security
        names.append(name)
        ror = Prices.playprices.ticker_ror(ticker, date, end)
        ror = '{:.2%}'.format(ror)
        rors.append(ror)
    return render(request,
                  'hindsight1/result.html',
                  context={'port_ror':port_ror,
                           'weights': weights,
                           'tickers': companies,
                           'date': date,
                           'strat_cum': strat_cum,
                           'names': names,
                           'rors': rors,
                           'user': user,
                           }
                  )
    
def play(request):
    #GameInputFormSet = formset_factory(GameInputForm, extra=5)
    if request.method == 'POST':
        #formset = GameInputFormSet(request.POST)
        form = GameInputForm(request.POST)
        #if formset.is_valid():
        if form.is_valid():
            weights=[]
            w1=form.cleaned_data.get('company_1')/100
            w2=form.cleaned_data.get('company_2')/100
            w3=form.cleaned_data.get('company_3')/100
            w4=form.cleaned_data.get('company_4')/100
            w5=form.cleaned_data.get('company_5')/100
            weights=[w1,w2,w3,w4,w5]
            #play_id = request.POST.get("play_id","")
            #save data into session and send to result view
            #request.session['play_id'] = request.POST.get("play_id","")
            request.session['weights'] = weights
            
            return HttpResponseRedirect(reverse('hindsight1:result'))
        else:
            HttpResponseRedirect(reverse('hindsight1:play'))
    else:
        #get user and current capital
        user = request.user
        #Instantiate a new play
        date, tickers = Prices.playprices.start_play(number=5)
        start = Prices.start_date(date)
        if user.is_authenticated:
            play = PlayRecord(play_rand_date=date, companies=tickers)
            play.user = user
            play.save()
            request.session['play_id'] = play.id
        #Store play info into session to pass into next view.
        request.session['companies'] = tickers
        #must save date info in session as integers, as datetimes cannot be
        #serialized by json
        request.session['year'] = date.year
        request.session['month'] = date.month
        request.session['day'] = date.day
        form=GameInputForm()
        prices=pd.DataFrame()
        data = {}
        col_names = ['Company 1', 'Company 2', 'Company 3', 'Company 4', 'Company 5']
        for idx, company in enumerate(tickers):
            data[col_names[idx]]={}
            prices_t=Prices.playprices.price_ts(company, start, date)
            prices=pd.concat([prices, prices_t], axis=1)
            data[col_names[idx]]['sector']=Sp100.playcompanies.get_sector(company)
            data[col_names[idx]]['industry']=Sp100.playcompanies.get_industry(company)
            
            
        prices.columns = col_names
        chart_div=chart.chart_line_base100(prices, formatchart='.2f', title='Price Return (rebased to 100)', size=[600,400])

            
        return render(request, 'hindsight1/playV5.html', context={'form': form,
                                                                #'play_id':play_id,
                                                                'chart_div': chart_div,
                                                                'user': user,
                                                                'data': data,
                                                                }
                    )        


def strategy_ts(prices, weights):
    rors=prices.pct_change(periods=1).fillna(value=0)
    strategy=rors.dot(weights)
    cum = pd.DataFrame((1+strategy).cumprod()-1, columns=['strategy'])
    return cum

hindsight1/templates/hindsight1/base_hindsight1.html
{% extends "base.html" %}

{% block css %}
{% load static %}

{% block extra_head %}
{% endblock extra_head %}

<link rel="stylesheet" type=text/css" href="{% static 'hindsight1/hindsight1.css' %}" />
{% endblock %}



{% block subtopmenu %}
<div class="subtopmenu">
  <ul>
    <li><a href="{% url 'hindsight1:ranking' %}"><b>ranking</b></a></li>	
    <li><a href="{% url 'hindsight1:play' %}"><b>new play</b></a></li>
    <li><a href="{% url 'hindsight1:dashboard' %}"><b>performance dashboard</b></a></li>	
  </ul>
</div>
{% endblock subtopmenu %}

{% block content %}


{% endblock content %}

hindsight1/templates/hindsight1/index_h1.html
{% load static %}

{# Load tag library, CSS and JS from bootstrap #}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}


<link rel="stylesheet" type"text/css" href="{% static 'hindsight1/style.css' %}" />

<div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-10">
    <h1>Index page for hindsight app</h1>
  </div>
 </div>
	
<form method="post" action="">{% csrf_token %}
    Hello, World! The sine of {{ form.r }}
    <input type="submit" value="equals" />
</form>

hindsight1/templates/hindsight1/myhome.html
{% extends "hindsight1/base_hindsight1.html" %}


{% block content %}

<h2 style="text-align:center">Performance Dashboard</h2>

<div class="dashboard">
<div>
  {{ past_chart|safe }}
  
</div>
<div>
  {{ cum_chart|safe }}
</div>
 
</div>

{% endblock content %}

hindsight1/templates/hindsight1/performance.html
{% extends "hindsight1/base_hindsight1.html" %}


{% block content %}

<h2 style="text-align:center">Performance Dashboard</h2>

<div class="dashboard">
<div>
  {{ past_chart|safe }}
  
</div>
<div>
  {{ cum_chart|safe }}
</div>
 
</div>

{% endblock content %}

hindsight1/templates/hindsight1/play.html
{% extends "./base.html" %}

{% block css %}
{% load static %}
<link rel="stylesheet" type=text/css" href="{% static 'hindsight1/style.css' %}" />
{% endblock %}

{% block content %}


<div class="row">
<div class="col-sm-1"></div>
<div class="col-sm-10">
  {{ chart_div|safe }}
</div>
<div class="col-sm-1"></div>
</div>


 <ul>
  {% for key, value in company_sector.items %}
	<li> {{ key }} </li>
    <li>Company {{ forloop.counter }} Sector: {{ value }} </li>
  {% endfor %} 
</ul>


<p>Date: {{ date }}</p>
 
<br>
 
<div class="row">
    <div class="col-sm-6">
        <form action="" method="post">
            {% csrf_token %}
            {{ formset.management_form }}

            <table>
                {% for form in formset %}
                <tr>
                  <td>{{ form.as_p }}</td>
                </tr>
                {% endfor %}

            </table>

            <input type="hidden" name="play_id" value="{{ play_id }}" >
            <input type="submit" value="Submit Allocation" >
        </form>
    </div>
</div>

{% endblock %}

hindsight1/templates/hindsight1/playV5.html
{% extends "hindsight1/base_hindsight1.html" %}
{% load humanize %}
{% load static %}

{% block extra_head %}

<link href="https://cdnjs.cloudflare.com/ajax/libs/rangeslider.js/2.3.0/rangeslider.min.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/rangeslider.js/2.3.0/rangeslider.min.js"></script>

{% endblock extra_head %}





{% block content %}


<div id="content">
    <button type="button" id="sidebarCollapse" class="btn btn-primary navbar-btn">
        <i class="glyphicon glyphicon-align-left"></i>
        Information
    </button>
</div>

<div class="game-container">

<nav id="sidebar">

{% if user.is_anonymous %}
<p> If you create a user, you can track your performance history in the performance
dashboard.
</p>
{% endif %}

<p>
This is a simple game that I set up as an exercise to learn
how to create apps with Django that leverage the simplicity of its web framework with Python's calculation and charting power. Most tutorials online teach how to set up simpler apps like blogs that have little business logic under the hood, so this game is my personal laboratory to experiment with these platforms and their integration.
</p>
</br>
<p>
The Rules are simple:
</p>
<ul>
<li>5 companies from the S&amp;P 100 and a date from 2010 to 
2017 are picked at random.</li>
<li> You can see each company's last 6 month price chart, and
their GICS sector + industry.</li>
<li> You must create a portfolio with these 5 companies, choosing
the weights for each one with the slider bar. Weights must add up to
100% and there is no shorting.</li>
<li> After submitting, you will be shown the return this simulated
portfolio would have had during the following 6 months, and the names
of each company.</li>
<li>You can see your return history and growth of a simulated $1,000,000
starting capital in the "Performance Dashboard" tab.</li>
</ul>


</nav>


<div class="main-game">

<div class="slider-list">

<form action="" method="post">{% csrf_token %}

{{ form.as_ul }}

<table class="slider-table">
  <tr>
    <td>Total Allocation: <output id="js-result"></output></td>
	<td><input type="submit" value="Submit Allocation" ></td>
  </tr>
</table>

  
<input type="hidden" name="play_id" value="{{ play_id }}" >

</form>
</div>
  


<div>  
{{ chart_div|safe }}
</div>

<div>
<table class="table table-striped table-sector">
  <tr>
    <th>Company</th>
    <th>Sector</th>
    <th>Industry</th>
  </tr>
  {% for company, items in data.items %}
  <tr>
    <th>Company {{ forloop.counter }} </th>
    <td>{{ items.sector }}</td>
    <td>{{ items.industry }}</td>
  </tr>
  {% endfor %}
</table>

</div>

</div>

</div>

{% endblock content %}

{% block javascript %}
<script src="{% static 'hindsight1/hindsight1.js' %}"></script>

{% endblock javascript %}

hindsight1/templates/hindsight1/ranking.html
{% extends "hindsight1/base_hindsight1.html" %}
{% load humanize %}


{% block content %}

<div class="ranking-container">


<div class="ranking-box">
    
<ol>
  {% for player in rank %}
    <li>{{ player.user }}: ${{ player.capital|floatformat:0|intcomma }}</li>
  {% endfor %} 
</ol>

</div>
</div>



{% endblock content %}

hindsight1/templates/hindsight1/result.html
{% extends "hindsight1/base_hindsight1.html" %}
{% load humanize %}


{% block content %}




<div class="main-game">
  {{ strat_cum|safe }}


<table class="result">
  <tr>
	<th></th>
	{% for name in names %}
	<th>Company {{ forloop.counter }} </th>
	{% endfor %}
  </tr>
  <tr>
	<th>Name</th>
	{% for name in names %}
	<td>{{ name }}</td>
	{% endfor %}
  </tr>
  <tr>
	<th>Weight</th>
	{% for weight in weights %}
	<td>{% widthratio weight 1 100 %}%</td>
	{% endfor %}
  </tr>
  <tr>
	<th>Price Return</th>
	{% for ror in rors %}
	<td>{{ ror }} </td>
	{% endfor %}
  </tr> 
</table>

</div>

{% endblock content %}

hindsight1/templates/hindsight1/topmenu.html
{% extends "./base.html" %}



{% block topmenu %}
<div class="row">
  <div class="col-sm-12">
  <ul>
    <li><a href="{% url 'hindsight1:index' %}">Home</a></li>
    <li><a href="{% url 'hindsight1:play' %}">Play</a></li>	  
    <li><a href="{% url 'hindsight1:index' %}">About Us</a></li>	  
  </ul>
  </div>
</div>

{% endblock topmenu %}