blog/urls.py
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 13 17:12:18 2017

@author: crist
"""

from django.conf.urls import url


from . import views

app_name = 'blog'

urlpatterns = [
        url(r'^index/$', views.index, name='index'),
        url(r'^search/$', views.search, name='search'),
        url(r'^(?P<post_id>[0-9]+)/$', views.detail, name='detail'),    
        url(r'^topic/(?P<topic>[\w\-]+)/$', views.topic, name='topic'),
        url(r'^tag/(?P<tag>[\w\-]+)/$', views.tags, name='tags'),
        ]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from .sitemaps import MainSitemap
from blog.sitemaps import BlogSitemap


urlpatterns = [
    url(r'^game/', include('hindsight1.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.about, name='home'),
    url(r'^myhome/(?P<username>[\w\-]+)/', views.myhome, name='myhome'),        
    url(r'^about/$', views.about, name='about'), 
]


#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),

]

#Add sitemapts

sitemaps = {
        'blog': BlogSitemap(),
        'main': MainSitemap(),
        }

urlpatterns += [
        url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

#Add Markdown
urlpatterns += [
    url(r'^markdownx/', include('markdownx.urls')),
]

#Add media path
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.postgres.fields import ArrayField

# Create your models here.

class Topic(models.Model):
    subject = models.CharField(max_length=200)

    def __str__(self):
        return self.subject   


class Post(models.Model):
    text = models.TextField(null=False, blank=True)
    post_title = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    pub_date = models.DateTimeField(default=timezone.now)
    last_update = models.DateField(auto_now=True)    
    summary = models.CharField(max_length=450)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    tags = ArrayField(models.CharField(max_length=50), default=list) 
    views = models.IntegerField(default=0)
    image = models.ImageField(upload_to='blog')

    #string for name
    def __str__(self):
        return self.post_title
    
    def get_absolute_url(self):
        return '/blog/'+str(self.id)+'/'

    

blog/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.contrib.postgres.search import SearchQuery, SearchRank, SearchVector

from .models import Post, Topic

def search(request):
    keywords = request.GET.get('q')
    
    qs = Post.objects.filter(pub_date__lte=timezone.now()).order_by('pub_date')
    
    if keywords:
        query = SearchQuery(keywords)
        title_vector = SearchVector('post_title', weight='A')
        content_vector = SearchVector('text', weight='B')
        vectors = title_vector + content_vector
        qs = qs.annotate(search=vectors).filter(search=query)
        qs = qs.annotate(rank=SearchRank(vectors, query)).order_by('-rank')
        
    return render(request,
                  'blog/index.html',
                  {'posts': qs})


def index(request):
    posts = Post.objects.filter(
                                pub_date__lte=timezone.now()
                                ).order_by('pub_date')
    return render(request,
                  'blog/index.html',
                  {'posts': posts})


def topic(request, topic):
    topicFilter = get_object_or_404(Topic, subject=topic)
    #topicFilter = Topic.objects.get(subject=topic)
    posts = Post.objects.filter(
                                topic=topicFilter, 
                                pub_date__lte=timezone.now()
                                ).order_by('pub_date')
    return render(request,
                  'blog/index.html',
                  {'posts': posts})


def tags(request, tag):
    posts = Post.objects.filter(
                                tags__contains=[tag],
                                pub_date__lte=timezone.now()
                                ).order_by('pub_date')
    return render(request,
                  'blog/index.html',
                  {'posts': posts})


def detail(request, post_id):
    post = Post.objects.get(pk=post_id)
    return render(request,
                  'blog/detail.html',
                  {'post': post})

blog/templates/blog/base_blog.html
{% extends "base.html" %}
{% load static %}

{% block css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/markdown.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'blog/blog.css' %}" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">


{% endblock %}

{% block content %}

<div id="content">
    <button type="button" id="sidebarCollapse" class="btn btn-primary navbar-btn ">
        <i class="glyphicon glyphicon-align-left"></i>
        Search
    </button>
</div>




<div class="main-container">
<nav id="sidebar">

    <div class="wrap">
       <div class="search">
         <form action="{% url 'blog:search' %}" method="get" accept-charset="utf-8">
          <input type="text" name="q" class="searchTerm" placeholder="Search posts">
          <button type="submit" class="searchButton">
            <i class="glyphicon glyphicon-search"></i>
          </button>
         </form>
       </div>
    </div>

	<!-- Sidebar Links -->
	<ul class="components sidebar-topics">
		<li class="active"><a href="{% url 'blog:index' %}">All Topics</a></li>
		<li><a href="{% url 'blog:topic' 'Lifestyle' %}">Travel &amp; Lifestyle</a></li>
		<li><a href="{% url 'blog:topic' 'Django' %}">Django</a></li>
		<li><a href="{% url 'blog:topic' 'Photography' %}">Photography</a></li>
	</ul>


</nav>


{% block post %}

{% endblock post %}


</div>
{% endblock content %}

{% block javascript %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="{% static 'blog/blog.js' %}"></script>
{% endblock javascript %}

blog/templates/blog/detail.html
{% extends "blog/base_blog.html" %}
{% load static %}
{% load markdownify %}


{% block post %}

<div class="post-content">

<h2>{{ post.post_title }}</h2>

<div class="highlight">
<p>{{ post.text | markdown | safe }}</p>
</div>
<p>Created: {{ post.created_at }}</p>

<p>Last update: {{ post.last_update }}</p>

    
<div id="disqus_thread"></div>
<script>



var disqus_config = function () {
this.page.url = "https://dodgingbias.com/blog/{{ post.id }}/"; 
this.page.identifier = '/blog/{{ post.id }}/';
};

(function() { 
var d = document, s = d.createElement('script');
s.src = 'https://dodgingbias.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                            

    
</div>



{% endblock post %}
 

blog/templates/blog/index.html
{% extends "blog/base_blog.html" %}
{% load static %}
{% load markdownify %}
{% load humanize %}


{% block post %}


<div class="index-container">

{% for post in posts %}


<div class="post-and-image"> 
  <div class="extras-container">
    <p id="extra-topic">{{post.topic }}</p>
	<p>{{post.pub_date|naturalday }}</p> 
    <span class="disqus-comment-count" data-disqus-identifier="/blog/{{post.id}}/"><!-- Count will be inserted here --> </span>

  </div>
  
  <div class="thumbnail">
    <img src="{{ post.image.url }}" />
  </div>

  <div id="summary">	  
    <h3><a href="{% url 'blog:detail' post.id %}" id="index-post-title">{{ post.post_title }}</a></h3>
    <p>{{post.summary }}</p>
    {% if post.tags %}
    <ul id="tags">
      <li><a href="{% url 'blog:tags' post.tags.0 %}">{{ post.tags.0 }}</a></li>
      <li><a href="{% url 'blog:tags' post.tags.1 %}">{{ post.tags.1 }}</a></li>
      <li><a href="{% url 'blog:tags' post.tags.2 %}">{{ post.tags.2 }}</a></li>
    </ul>
    {% endif %}  
  </div>

  
</div>

  
{% endfor %}



</div>
    
  <script id="dsq-count-scr" src="//dodgingbias.disqus.com/count.js" async></script>


{% endblock post %}
 

blog/templates/blog/topic.html
{% extends "blog/base_blog.html" %}
{% load static %}
{% load markdownify %}


{% block post %}
<div class="post-container">

<div class="container-fluid">


{% for post in topic %}

<div class="row">
<div class="col-md-8 col-md-offset-2">

  <h3><a href="{% url 'blog:detail' post.id %}" id="post-title">{{ post.post_title }}</a></h3>
  <p id="summary">{{post.summary }}</p>
  <p id="extra-info">Topic: {{post.topic }} - Published: {{post.created_at }}</p>  

</div>
</div>
  
{% endfor %}



</div>

</div>
{% endblock post %}
 