blog/urls.py
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 13 17:12:18 2017

@author: crist
"""

from django.conf.urls import url


from . import views

app_name = 'blog'

urlpatterns = [
        url(r'^index/$', views.index, name='index'),
        url(r'^search/$', views.search, name='search'),
        url(r'^(?P<post_id>[0-9]+)/$', views.detail, name='detail'),    
        url(r'^topic/(?P<topic>[\w\-]+)/$', views.topic, name='topic'),
        url(r'^tag/(?P<tag>[\w\-]+)/$', views.tags, name='tags'),
        ]

hindsight1/urls.py
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 13 17:12:18 2017

@author: crist
"""

from django.conf.urls import url

from . import views

#this tells django these urls belong to the 'hindsight1' app, when referencing
#from a template with the {%url%} tag. 
app_name = 'hindsight1'

urlpatterns = [url(r'^game/$', views.ranking, name='ranking'),
              url(r'^result/$', views.result, name='result'),
              url(r'^play/$', views.play, name='play'),
              url(r'^ranking/$', views.ranking, name='ranking'),
              url(r'^dashboard/$', views.perf_dashboard, name='dashboard'),
              
              
              
              ]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from .sitemaps import MainSitemap
from blog.sitemaps import BlogSitemap


urlpatterns = [
    url(r'^game/', include('hindsight1.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.about, name='home'),
    url(r'^myhome/(?P<username>[\w\-]+)/', views.myhome, name='myhome'),        
    url(r'^about/$', views.about, name='about'), 
]


#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),

]

#Add sitemapts

sitemaps = {
        'blog': BlogSitemap(),
        'main': MainSitemap(),
        }

urlpatterns += [
        url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

#Add Markdown
urlpatterns += [
    url(r'^markdownx/', include('markdownx.urls')),
]

#Add media path
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE HTML>
<html lang="en">

<head>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-113143925-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-113143925-1');
</script>

    
{% load static %}

{# Load tag library, CSS and JS from bootstrap #}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}


<link href="https://fonts.googleapis.com/css?family=Bitter|Fira+Sans|Lato|Abril+Fatface|Catamaran|Karla|Merriweather+Sans|Roboto+Mono|Supermercado+One|Archivo+Black" rel="stylesheet">


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css"></script>
<link rel="stylesheet" type="text/css" href="{% static 'mysite/style.css' %}" />
    
<script src="https://use.fontawesome.com/f5f6e30fff.js"></script>

{% block css %}{% endblock %}

<title>Cristobal Aguirre</title>
  <meta name="description" content="A blog on Python, Django, Data Science, Economics, and our life in Vancouver.">

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name=viewport content="width=device-width, initial-scale=1">
    
<link rel="icon" type="image/png" href="{% static 'mysite/favicon.png' %}" />

    

</head>


{% block topmenu %}

<div class="topmenu">
  <ul class="topmenu-left">
    <li><a href="{% url 'about' %}"><b>HOME</b></a></li>
    <!--<li><a href="{% url 'hindsight1:play' %}">GAME</a></li>	!-->
    <li><a href="{% url 'blog:index' %}">BLOG</a></li>	
    </ul>
  </div>

{% endblock topmenu %}

{% block subtopmenu %}
{% endblock subtopmenu %}

<body>

{% block content %}
{% endblock content %}


</body>

{% block footer %}
<footer>

<div class="footer-left">
    
<span class="license">
This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>
</span>
    
</div>

<div class="footer-right">
    <a href="https://github.com/jcaguirre89/" target="_blank">
    <i class="fa fa-github social-icon fa-3x" aria-hidden="true"></i>
    </a>
    
    <a href="https://www.linkedin.com/in/cristobal-aguirre-cfa/" target="_blank">
    <i class="fa fa-linkedin-square social-icon fa-3x" aria-hidden="true"></i>
    </a>
</div>

    
    
</footer>
{% endblock footer %}

{% block javascript %}{% endblock %}

</html>